### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by torwag** [kuehnelbs/node-red-contrib-nextcloud#3]
Hi,
thanks for the project. It looks really promising to bring my nextcloud and home automation stuff together. 
Naturally, I am most interested in the calendar function.
If I get it right, the node will provide an array of ALL calendar entries. Beside of the fact that this might be a lot of data, I was wondering if it would be possible to give a start and end date via the incoming payload.
This would also help a lot for parsing the array. Furthermore, relative values would be nice, like setting the end-date to be +7, which reads... 7 days from now.

I am aware we can achieve this within node-red itself, but having it "build-in" would make it even easier to use this contrib.

**Comment by kuehnelbs** [comment]
Hi torwag,
you're right - you get all calendar entries of all calendars (if no calendar specified) and parsing takes a lot of time and is mostly unneccessary for expired entries. I will have a look at dov filters: time-range allows start and end. And of course it makes sense to define a +/- offset from now to set the time range.

**Comment by kuehnelbs** [comment]
Thx to @basti76  this issue has been fixed
